apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: ert
        image: swr.cn-south-1.myhuaweicloud.com/kube-ert/ert-server
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: my-secret